bpmn-io/bpmnlint

- README.md
Keep configuration to a bare minimum to not confuse users.
Feature extending from `bpmnlint:recommended`.
> docs(README): simplify

- lib/utils.js
- rules/end-event-required.js
- rules/start-event-required.js
- test/rules/end-event-required.js
- test/rules/end-event-required/invalid-sub-process.bpmn
- test/rules/end-event-required/invalid.bpmn
- test/rules/end-event-required/valid-sub-process.bpmn
- test/rules/end-event-required/valid.bpmn
- test/rules/start-event-required.js
- test/rules/start-event-required/invalid-sub-process.bpmn
- test/rules/start-event-required/invalid.bpmn
- test/rules/start-event-required/valid-sub-process.bpmn
- test/rules/start-event-required/valid.bpmn
- test/spec/utilsSpec.js
> Test existing rules

- lib/linter.js
- test/integration/bpmnlint-plugin-test-ns/index.js
- test/integration/bpmnlint-plugin-test-ns/package.json
- test/integration/bpmnlint-plugin-test-ns/rules/no-label-xxx.js
- test/integration/cli-spec.js
- test/integration/cli/ns/diagram-invalid.bpmn
- test/integration/cli/ns/diagram.bpmn
- test/integration/cli/ns/extends.json
- test/integration/cli/ns/package.json
- test/integration/cli/ns/uses-rules.json
- test/spec/linter-spec.js
- test/spec/support/compile-config-spec.js
Intended to support scoped packages as highlighted in Issue https://github.com/bpmn-io/bpmnlint/issues/35.
Closes #35
> feat: support scoped rules

- .travis.yml
- docs/rules/no-inclusive-gateway.md
Related to #41
Closes #44
__Definition of Done__
> Add explanation to no-inclusive-gateway rule

- .github/workflows/ci.yml
Preparation to replace Travis CI.
> chore: add GitHub <ci> action

- .github/workflows/CI.yml
* updates action name and build step
* removes additional caching keys. We do not know if they work, at all
> chore: align CI action

- bin/bpmnlint.js
- lib/test-rule.js
- rules/conditional-flows.js
- rules/event-sub-process-typed-start-event.js
- rules/label-required.js
- rules/single-event-definition.js
- rules/sub-process-blank-start-event.js
- test/rules/conditional-flows.js
- test/rules/event-sub-process-typed-start-event.js
- test/rules/label-required.js
- test/rules/single-event-definition.js
- test/rules/sub-process-blank-start-event.js
- test/spec/test-rule-spec.js
> feat: allow path property in Reporter#report

- CHANGELOG.md
* `FEAT`: fuzzy test for equality of nodes when using `RuleTester#verify` ([#79](https://github.com/bpmn-io/bpmnlint/pull/79/files))
> chore(CHANGELOG): update to v7.7.0

- rules/no-bpmndi.js
- test/rules/no-bpmndi.js
- test/rules/no-bpmndi/invalid-message-flow.bpmn
- test/rules/no-bpmndi/valid-message-flow.bpmn
> feat(no-bpmndi): detect messageflows without di

- bin/bpmnlint.js
- package-lock.json
- test/integration/cli-spec.js
- test/integration/cli/diagram-warnings.bpmn
> Max warnings

- README.md
> docs: document API usage

- lib/linter.js
- test/spec/linter-spec.js
- test/spec/support/compile-config-spec.js
Adds `info` type requested by various parties.
> feat: support `info` type

- rules/no-implicit-end.js
- rules/no-implicit-start.js
- test/rules/no-implicit-end.js
- test/rules/no-implicit-end/invalid.bpmn
- test/rules/no-implicit-end/valid-collaboration.bpmn
- test/rules/no-implicit-end/valid.bpmn
- test/rules/no-implicit-start.js
- test/rules/no-implicit-start/invalid.bpmn
- test/rules/no-implicit-start/valid-collaboration.bpmn
- test/rules/no-implicit-start/valid.bpmn
This ensures we properly handle additional scenarios for the newly introduced [`no-implicit-end`](https://github.com/bpmn-io/bpmnlint/commit/e03c12075898260a5212c0194a2274e799dce645) and [`no-implicit-start`](https://github.com/bpmn-io/bpmnlint/commit/ef5a3f29ab055fd58bbaeb6b42c437c016443456) rules.
----
Closes https://github.com/bpmn-io/bpmnlint/issues/105
> Fix implicit rules

- CHANGELOG.md
- lib/linter.js
- test/spec/linter-spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3637
> Introduce `rule-error` Category for Rule Errors

- CHANGELOG.md
> chore(CHANGELOG): update to v9.0.0

- docs/rules/no-bpmndi.md
Related to https://github.com/camunda/camunda-modeler/issues/4277.
> docs: improve `no-bpmndi` phrasing

- rules/no-overlapping-elements.js
- test/rules/no-overlapping-elements.mjs
- test/rules/no-overlapping-elements/valid-data-objects.bpmn
Closes https://github.com/bpmn-io/bpmnlint/issues/133
> Verify data object handling in `no-overlapping-elements` rule

- lib/testers/rule-tester.d.ts
This gives users a chance for auto-completion as they implement their rule tests.
> feat: type `RuleTester#verify` API

- test/integration/bundling/test/app.webpack.expected.js
This updates the test fixtures for webpack so CI passes again.
> test: update webpack expected bundle

- package-lock.json
- package.json
It looks that this is unnecessary.
Related to https://github.com/bpmn-io/bpmnlint/commit/70998a04502c354b22a457306343f9a0a4892e4b#r150399905
> chore: remove self-link from deps

- CHANGELOG.md
- package-lock.json
- package.json
> Housekeeping

- test/integration/bundling/test/app.webpack.expected.js
Order of bundled files changed, likely due to a node patch bump. No changes in dependencies since [previous CI run](https://github.com/bpmn-io/bpmnlint/actions/runs/12581627691/job/35065759790).
> test: update webpack test fixtures

- lib/linter.js
- package-lock.json
- package.json
The `console` global is now provided OOTB as part of the recommended rule set.
Follow-up to https://github.com/bpmn-io/bpmnlint/pull/168.
> chore: bump eslint-plugin-bpmn-io

- config/correctness.js
- test/spec/config-spec.mjs
Proposes the `correctness` ruleset for all true lovers of BPMN (with execution semantics).
Closes https://github.com/bpmn-io/bpmnlint/issues/170
> feat: add `correctness` rule set

- README.md
- config/correctness.js
- test/spec/config-spec.mjs
Related to https://github.com/camunda/camunda-modeler/issues/5044
include `single-blank-start-event` & `start-event-required` rule in correctness config:|
- https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/start-event-required.md
- https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/single-blank-start-event.md
> Adjust correctness config

- rules/no-gateway-join-fork.js
Fix documentation link
```json
"no-gateway-join-fork": [
{
"id": "Gateway",
"message": "Gateway forks and joins",
"meta": {
"documentation": {
"url": "https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/no-gateway-join-fork.md"
}
},
"category": "error"
}
],
```
> Adjust documentationUrl for no-gateway-join-fork
