lib/resolver/nodeResolver.js
test/spec/resolver/nodeResolverSpec.js

It is an interesting question whether or not we should force a common prefix for all `bpmnlint` related extension libraries. This PR adds the functionality by prefixing resolved rules and configurations with a `bpmnlint-plugin-` prefix.

chore(resolver): resolve extensions via prefix

---

rules/no-disconnected.js
test/rules/no-disconnected.js
test/rules/no-disconnected/valid-event-subprocess.bpmn

Fixes #31 
By definition, it does not make sense for event triggered sub events to be check with no-disconnected rule:

fix(lint): Exclude event triggered subprocesses from no-disconnected rule

---

.travis.yml

Testing the library on Windows and MacOS, too.
Ref: https://github.com/bpmn-io/bpmnlint/pull/47

chore(ci): add macos and windows test environments

---

lib/support/compile-config.js
lib/test-rule.js
lib/traverse.js
test/spec/linter-spec.js
test/spec/test-rule-spec.js
test/spec/traverse-spec.js

A rule can now be explicit about when to check a given node, on _enter_, on _leave_ or during both occasions:
```javascript
module.exports = function someRule() {
return {
check: {
enter: function(node, reporter) { ... },
leave: function(node, reporter) { ... }
}
};
};
```
A rule may also return false from the _enter_ hook to stop traversing deeper into the elements children.
---
Closes https://github.com/bpmn-io/bpmnlint/issues/52
Closes https://github.com/bpmn-io/bpmnlint/issues/53

Implement <enter> and <leave> hooks as well as sub-tree skipping

---

rules/no-disconnected.js
test/rules/no-disconnected.js
test/rules/no-disconnected/valid-compensation.bpmn

These elements must be checked separately for a association.

fix(rules/no-disconnected): exclude compensation task and boundary

---

bin/bpmnlint.js
test/integration/cli-spec.js

Ensures the cli reports the bpmnlint version if asked to do so via
the standard `--version` switch.

feat: support `--version` switch

---

lib/testers/rule-tester.js
rules/no-bpmndi.js
test/rules/no-bpmndi.js
test/rules/no-bpmndi/valid-no-lanes.bpmn

Closes https://github.com/bpmn-io/bpmnlint/issues/63.

Ensure `no-bpmndi` does not blow up on missing `LaneSet#lanes`

---

lib/resolver/node-resolver.js
lib/support/compile-config.js
test/spec/resolver/node-resolver-spec.js
test/spec/support/compile-config-spec.js

This PR ensures that rules implemented locally are also resolved locally within the package.
To do that we check for a local `package.json`. If it exists we use the package name to normalize required configs and rules.
Adjustment must be done both when resolving rules as well as when compiling the linter configuration.
----
Given this enhancements local rules can be safely referenced by name (of the package):
```
bpmnlint-plugin-foobar
-> index.js
-> .bpmnlintrc = { "extends": "plugins:foobar/recommended" }
```
---
How to try out:
```sh
git clone https://github.com/bpmn-io/bpmnlint-plugin-example
cd bpmnlint-plugin-example
echo '{ "extends": "plugin:example/recommended" }' > .bpmnlintrc
npx bpmnlint@bpmn-io/bpmnlint#local-package-resolution some-bpmn-diagram.bpmn
```

feat: resolve local package by name

---

lib/testers/rule-tester.js
test/rules/conditional-flows.js
test/spec/testers/rule-tester-spec.js

Improves console output from
```sh
rules/camunda-cloud-1-0-integration
should lint valid
√ test case #1
√ test case #2
√ test case #3
```
to
```sh
rules/camunda-cloud-1-0-integration
should lint valid
√ test case #1 bpmndi elements
√ test case #2 parse collaborations
√ test case #3 conditional sequence flows
```
---
Closes #67

feat: add optional name to tests through RuleTester.verify

---

lib/test-rule.js
test/integration/cli-spec.js
test/spec/test-rule-spec.js

Provide additional information by providing object as third argument.
```js
Reporter.report('foo', 'Foo error', [ 'foo', 'bar', 'baz' ]);
Reporter.report('foo', 'Foo error', {
path: [ 'foo', 'bar', 'baz' ],
foo: 'foo'
});
```

Provide Additional Information when Calling `Reporter#report`

---

lib/testers/rule-tester.js
test/spec/testers/rule-tester-spec.js

Takes into account that reports might include instances of [`Base`](https://github.com/bpmn-io/moddle/blob/master/lib/base.js). Instances are replaced by ID or type allowing for tests like the following:
```js
RuleTester.verify('foo', rule, {
[],
[
{
moddleElement: ...,
report: {
id: 'Task_1'
message: 'Foo',
node: 'Task_1' // instance replaced by ID
}
}
]
});
```

feat(rule-tester): fuzzy test for equality of moddle elements

---

lib/linter.js
test/spec/linter-spec.js

Configuration was already a feature. The only missing piece was passing the configuration to the rule factory.
Closes #78

feat: pass configuration to rule factory

---

lib/testers/rule-tester.js
test/spec/testers/rule-tester-spec.js

Allows configurable rules to be tested.
```javascript
RuleTester.verify('my-rule', myRule, {
valid: [],
invalid: [
{
name: 'with config',
config: {
elements: [ 'bpmn:Task' ]
},
moddleElement: createModdle('<bpmn:Task id="Task_1" />', 'bpmn:Task'),
report: {
id: 'Task_1',
message: 'Element of type <bpmn:Task> detected'
}
}
]
});
```

feat: rule tester accepts local config

---

CHANGELOG.md

* `FEAT`: detect messageflows without DI ([#85](https://github.com/bpmn-io/bpmnlint/pull/85))
* `DEPS`: depend on @bpmn-io/moddle-utils ([`31de95a3`](https://github.com/bpmn-io/bpmnlint/commit/31de95a349fb3784d2b51e3b4071abc1d82d8d7a))

chore(CHANGELOG): update to v7.9.0

---

config/recommended.js

Known categories are `error` and `warn`.

fix: fix category in recommended config

---

docs/rules/examples/no-bpmndi-correct.bpmn
docs/rules/examples/no-bpmndi-incorrect.bpmn
docs/rules/examples/no-implicit-split-correct.bpmn

The rule [no-implicit-split](https://github.com/bpmn-io/bpmnlint/blob/master/docs/rules/no-implicit-split.md) should show a parallel gateway instead of an exclusive gateway as correct usage. The text also describes that a parallel gateway should be used.
I changed the bpmn file for the correct model but I was not sure how to regenerate the corresponding png file for the documentation.

Change exclusive gateway to parallel gateway in no-implicit-split rule documentation

---

lib/resolver/node-resolver.js
lib/support/compile-config.js
test/integration/bpmnlint-plugin-exported/package.json
test/integration/bpmnlint-plugin-exported/src/bar.js
test/integration/bpmnlint-plugin-exported/src/foo.js
test/integration/bpmnlint-plugin-exported/src/index.js
test/integration/bundling-spec.js
test/integration/bundling/package.json
test/integration/bundling/src/.bpmnlintrc
test/integration/bundling/test/app.rollup.expected.js
test/integration/bundling/test/app.webpack.expected.js
test/integration/cli-spec.js
test/integration/cli/exported.json
test/integration/cli/package.json
test/spec/resolver/node-resolver-spec.js
test/spec/support/compile-config-spec.js

Gives plugin authors the freedom to choose their own plugin structure (cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/87).
Example:
```javascript
module.exports = {
rules: {
baz: './foo/bar/baz'
}
};
```
[Similar to ESLint](https://eslint.org/docs/latest/extend/plugins#rules-in-plugins), just supporting path references over `require` calls; require calls cannot easily be bundled for the browser, cf. https://github.com/bpmn-io/bpmnlint/pull/99#discussion_r1154061535, https://github.com/bpmn-io/bpmnlint/pull/99#issuecomment-1521983034.
---
Related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/87

Resolve Explicitly Exported Plugin Rules

---

.eslintignore
.github/workflows/CI.yml
lib/support/compile-config.js
test/integration/compilation/.gitignore
test/integration/compilation/compile.js
test/integration/compilation/package.json
test/integration/compilation/test/bpmnlintrc.expected.js
test/integration/compile-spec.js

This fixes https://github.com/bpmn-io/bpmnlint/issues/112, which turned out to be a :window: only issue.
As it stands we need to properly convert paths between :window: and :penguin: _before_ we normalize or join, as these node utilities do a bad (to no) job of converting.

Fix compilation on Windows

---

lib/support/compile-config.js
test/integration/bundling/test/app.webpack.expected.js
test/integration/compilation/test/bpmnlintrc.expected.js
test/integration/compile-spec.js
test/spec/support/compile-config-spec.js

Previously we would use the absolute path to compile packages with custom paths.
This PR changes the behavior to compile to package local imports.

Compile rules using package local imports

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/NEW_RULE.md

chore(ISSUE_TEMPLATE): update formatting

---

rules/no-implicit-start.js
test/rules/no-implicit-start/valid.bpmn

This is currently marked as violating `no-implicit-start` rule while compensation activities can never have an incoming sequence flow.

fix: don't mark compensation activity as implicit start

---

rules/no-overlapping-elements.js
test/rules/no-overlapping-elements.mjs
test/rules/no-overlapping-elements/ignore-missing-di.bpmn

The linter would otherwise blow up.

Fix `no-overlapping-elements` to handle missing child element DI

---

rules/label-required.js
test/integration/bundling/test/app.rollup.expected.js
test/integration/bundling/test/app.webpack.expected.js
test/rules/label-required.mjs
test/rules/label-required/invalid-boundary-event.bpmn

Closes #141
Boundary events now requires label

fix: boundary event labels

---

rules/helper.js
rules/no-implicit-end.js
test/rules/no-implicit-end/valid.bpmn

fix: no no-implicit-end error on compensation activity

---

rules/global.js
test/rules/global/valid-message.bpmn

fix: send/receive task unused global

---

.github/workflows/CI.yml
CHANGELOG.md
package-lock.json
package.json

Update the requirement for node to Node@20. This is [soon the legacy node version](https://nodejs.org/en/about/previous-releases), so I think lifting up our requirements is fine.
At this stage this will simply indicate the incompatibility when upgrading `bpmnlint`. It will still _work_ on node@16, though we don't guarantee it anymore, going into the future.
----
Additional context:
* Internally, for development, we already use Node@20 for a long time
* Certain upgrades, such as [migrating from the now unmaintained `eslint@8` to `@9`](https://github.com/bpmn-io/bpmnlint/pull/148) require us also to upgrade to node@20

Require Node@20

---

rules/no-overlapping-elements.js
test/rules/no-overlapping-elements.mjs
test/rules/no-overlapping-elements/ignore-missing-bounds.bpmn

I've been running into some cases where some elements in the diagram don't have matching `bounds` in the DI, which lead the `no-overlapping-elements`  rule crash with a `rule-error`:
```js
rule <no-overlapping-elements> failed with error:  TypeError: Cannot read properties of undefined (reading 'bounds')
at checkElementsArray (/Users/marcoroth/Development/bpmnlint/rules/no-overlapping-elements.js:111:45)
at /Users/marcoroth/Development/bpmnlint/rules/no-overlapping-elements.js:28:9
at Array.forEach (<anonymous>)
at check (/Users/marcoroth/Development/bpmnlint/rules/no-overlapping-elements.js:26:8)
at traverse.enter (/Users/marcoroth/Development/bpmnlint/lib/test-rule.js:70:30)
at traverse (/Users/marcoroth/Development/bpmnlint/lib/traverse.js:18:33)
at testRule …
```

fix(no-overlapping-elements): skip when an element is missing `bounds`

---

rules/no-bpmndi.js
test/rules/no-bpmndi.mjs
test/rules/no-bpmndi/ignore-edge-without-bpmn-element.bpmn

Following #154, I've found another case where the `no-bpmndi` rule breaks. When a `BPMNEdge` or `BPMNShape` has a `bpmnElement` attribute which doesn't match to any element in the diagram it would crash the rule, leading to a `rule-error`:
```js
rule <no-bpmndi> failed with error:  TypeError: Cannot read properties of undefined (reading 'id')
at /Users/marcoroth/Development/bpmnlint/rules/no-bpmndi.js:112:36
at Array.map (<anonymous>)
at /Users/marcoroth/Development/bpmnlint/rules/no-bpmndi.js:110:25
at Array.map (<anonymous>)
at getAllDiBpmnReferences (/Users/marcoroth/Development/bpmnlint/rules/no-bpmndi.js:106:37)
at check (/Users/marcoroth/Development/bpmnlint/rules/no-bpmndi.js:28:30)
at traverse.enter (/Users/marcoroth/Development/bpmnlint/lib/test-rule.js:70:30)
at traverse …
```

fix(no-bpmndi): handle missing `bpmnElement` on `BPMNEdge` or `BPMNShape`

---

lib/test-rule.js
test/spec/linter-spec.mjs

We now clearly indicate that <enter> and <leave> are not provided, when an empty object is being returned as `check`.
Depends on https://github.com/bpmn-io/bpmnlint/pull/164 for :green_circle: CI.

chore: improve error message on missing rule hooks

---

lib/linter.js
lib/types.d.ts
test/spec/linter-spec.mjs

As described in https://github.com/bpmn-io/bpmnlint/issues/18, this allows rule authors to configure `meta` in a rule. The meta-data will be passed along with reports so downstream integrators, can, i.e. ship custom documentation URLs with their rules (https://github.com/camunda/camunda-modeler/issues/4491).
```javascript
module.exports = function(config) {
return {
meta: {
documentation: {
url: 'https://github.com/bpmn-io/bpmnlint'
}
},
check: (node, reporter) => {
...
}
};
};
```
This PR is comprised in two parts:
* https://github.com/bpmn-io/bpmnlint/commit/038a2cbfbfb0bf3b92a98be1c78d8c03bf0ea0e5 adds `meta` support
* https://github.com/bpmn-io/bpmnlint/commit/95be026251554f0392363a2aed25bf4fb19bb868 adds a transform hook that allows integrators to attach and/or modify existing rules …

Be able to configure meta-data with rules (and pass them to reports)

---

eslint.config.mjs
lib/linter.js
lib/resolver/node-resolver.js
package-lock.json
package.json

Follow up to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/188#discussion_r1959540810, this ensures we expose environment agnostic rules and implementation.

chore: ensure lib files are environment agnostic

---

lib/testers/rule-tester.js
rules/ad-hoc-sub-process.js
rules/conditional-flows.js
rules/end-event-required.js
rules/event-sub-process-typed-start-event.js
rules/fake-join.js
rules/global.js
rules/helper.js
rules/label-required.js
rules/link-event.js
rules/no-bpmndi.js
rules/no-complex-gateway.js
rules/no-disconnected.js
rules/no-duplicate-sequence-flows.js
rules/no-gateway-join-fork.js
rules/no-implicit-end.js
rules/no-implicit-split.js
rules/no-implicit-start.js
rules/no-inclusive-gateway.js
rules/no-overlapping-elements.js
rules/single-blank-start-event.js
rules/single-event-definition.js
rules/start-event-required.js
rules/sub-process-blank-start-event.js
rules/superfluous-gateway.js
rules/superfluous-termination.js
test/integration/bundling/test/app.rollup.expected.js
test/integration/bundling/test/app.webpack.expected.js
test/rules/link-event.mjs
test/spec/testers/rule-tester-spec.mjs

Builds on top of #165 to provide documentation URL with built-in rules.
* FIX: rule tester did not properly validate `meta` - https://github.com/bpmn-io/bpmnlint/commit/3041995b30255a6ad535d00b105f28161d827307
* FEAT: attach project documentation URL to built-in rules - https://github.com/bpmn-io/bpmnlint/commit/a4c73092d4a0d059170db47da1ce2ff7e34fd60c
Closes https://github.com/bpmn-io/bpmnlint/issues/166

Add documentation URL to built-in rules

---

test/integration/cli-spec.mjs
test/integration/cli/local-rules/.bpmnlintrc
test/integration/cli/local-rules/diagram.bpmn
test/integration/cli/local-rules/lib/bpmnlint-plugin/index.js
test/integration/cli/local-rules/lib/bpmnlint-plugin/package.json
test/integration/cli/local-rules/lib/bpmnlint-plugin/rules/no-label-bar.js
test/integration/cli/local-rules/package.json

Related to https://github.com/bpmn-io/bpmnlint/issues/81, this PR ensures there is a tested scenario available that shows how rules can be provided locally as part of an application. The solution is straight forward:
* Develop your rules in a sub-directory of your application, as if it was a bpmnlint plug-in
* Link (alias) the folder in your main application package, i.e. call it `bpmnlint-plugin-local`
* Reference the plug-in as `local` in wherever places you need
* :moneybag: 

Verify resolution of local plug-in + rules

---

rules/helper.js
rules/no-complex-gateway.js
rules/no-inclusive-gateway.js
test/integration/bundling/test/app.rollup.expected.js
test/integration/bundling/test/app.webpack.expected.js
test/rules/no-complex-gateway.mjs
test/rules/no-inclusive-gateway.mjs

Rather than calling out elements as "disallowed", frame element types as being "discouraged". This plays more nicely with different severity levels that folks can attach to lint results.
```
INFO    GATEWAY_1    Element type <bpmn:InclusiveGateway> is discouraged
```
```
ERROR   GATEWAY_1    Element type <bpmn:InclusiveGateway> is discouraged
```
Try out using the following command:
```
npx @bpmn-io/sr bpmn-js-bpmnlint -l bpmn-io/bpmnlint#element-type-discouraged
```
---
Related to [this conversation](https://camunda.slack.com/archives/C0693F1NFK5/p1740494040484239?thread_ts=1703070019.157809&cid=C0693F1NFK5).

Rework warning on elements that should not be used

---

rules/end-event-required.js
rules/start-event-required.js
test/integration/bundling/test/app.rollup.expected.js
test/integration/bundling/test/app.webpack.expected.js
test/rules/end-event-required.mjs
test/rules/end-event-required/invalid-sub-process-sub-types.bpmn
test/rules/end-event-required/valid-sub-process-sub-types.bpmn
test/rules/start-event-required.mjs
test/rules/start-event-required/invalid-sub-process-sub-types.bpmn
test/rules/start-event-required/valid-sub-process-sub-types.bpmn

AdHoc SubProcess must not have start or end event, so we should not require them to be present.
Closes #175

fix: do not require start and end event in ad-hoc subprocess

---

README.md

This should clear out some issues users are seeing around plug-in naming.

docs: clarify custom plug-in naming and referencing

---

docs/rules/ad-hoc-sub-process.md
rules/ad-hoc-sub-process.js
test/rules/ad-hoc-sub-process.mjs

Related to https://github.com/camunda/camunda-modeler/issues/4985
Only check that intermediate *catch* events have outgoing sequence flow. intermediate *throw* events don't necessarily need outgoing sequence flow.

fix: only check catch events in adhoc

---

bin/bpmnlint.js
lib/resolver/helper.js
lib/resolver/node-resolver.js
test/integration/bpmnlint-plugin-test-camunda/index.js
test/integration/bpmnlint-plugin-test-camunda/package.json
test/integration/bpmnlint-plugin-test-camunda/rules/no-service-task-like.js
test/integration/cli-spec.mjs
test/integration/cli/moddle-extension/.bpmnlintrc
test/integration/cli/moddle-extension/bpmnlintrc-missing-extension.json
test/integration/cli/moddle-extension/bpmnlintrc-relative-extension.json
test/integration/cli/moddle-extension/diagram.bpmn
test/integration/cli/moddle-extension/package-lock.json
test/integration/cli/moddle-extension/package.json

This allows users to declare `moddleExtensions` in the ROOT bpmnlint configuration file.
Nested configurations are not supported for the moment, but may be supported at some stage.
Implements what is sketched via https://github.com/bpmn-io/bpmnlint/issues/62
Implementation and integration tests ensure that extension is loaded locally to the actual bpmnlint configuration (and the project to be tested). 
Closes https://github.com/bpmn-io/bpmnlint/issues/62
Closes https://github.com/bpmn-io/bpmnlint/issues/8

Allow to set moddle extensions in the config
